-- Seed the previously-hardcoded SMS/A2P sections into the DB content
-- so the Terms and Privacy pages aren't missing content after the code change
-- NOTE: site_settings.value is JSONB, so strings must be JSON-encoded

-- Add last-updated dates
INSERT INTO site_settings (key, value) VALUES ('terms_last_updated', '"February 24, 2026"'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO site_settings (key, value) VALUES ('privacy_last_updated', '"February 24, 2026"'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Append SMS Terms section to terms_content (if it doesn't already contain it)
UPDATE site_settings
SET value = to_jsonb(
  (value #>> '{}') || E'\n\n---\n\n## SMS/Text Messaging Terms\n\n### Description of SMS Use Cases\n\nSTR Fitness LLC we are DBA as STR offers an SMS/text messaging program to provide members and prospective members with:\n\n- **Inquiry responses:** Replies to questions submitted through our website forms\n- **Appointment reminders:** Notifications about upcoming classes, training sessions, and scheduled visits\n- **Account updates:** Membership status, payment confirmations, and account changes\n- **Service notifications:** Schedule changes, facility updates, and class cancellations\n- **Promotional messages:** Special offers, events, and gym updates (only with explicit consent)\n\n### Opt-Out Instructions\n\nYou may opt out of receiving text messages at any time by:\n\n- Replying **STOP** to any text message from STR\n- Emailing info@trainwithstr.com with the subject "SMS Opt-Out"\n- Contacting us at 8 Eastman St, Suite 3, Cranford, NJ 07016\n\nAfter opting out, you will receive a one-time confirmation message. No further texts will be sent unless you re-subscribe.\n\n### Message & Data Rate Disclosure\n\nStandard message and data rates from your wireless carrier may apply to text messages you send to and receive from STR. Please contact your wireless carrier for details about your specific texting plan and any charges that may apply. STR is not responsible for any fees charged by your carrier.\n\n### Message Frequency\n\nMessage frequency varies depending on your interactions and account activity. You may receive up to 10 messages per month. Recurring messages may be sent for appointment reminders, account updates, and promotional content (if opted in).\n\n### Carrier Liability Disclaimer\n\nWireless carriers are not liable for delayed or undelivered messages. STR and its messaging service providers are not responsible for any delays, failures, or errors in the delivery of text messages, including messages sent through SMS, MMS, or other messaging formats. Delivery is subject to effective transmission from your wireless carrier. T-Mobile is not liable for delayed or undelivered messages.\n\n### Age Restriction\n\nYou must be at least 18 years of age to opt in to receive text messages from STR. If you are under 18, please do not provide your phone number or opt in to our messaging program without parental consent.\n\n### Customer Support\n\nFor help or questions about our text messaging program, you may:\n\n- Reply **HELP** to any text message\n- Email us at info@trainwithstr.com\n- Visit us at 8 Eastman St, Suite 3, Cranford, NJ 07016\n\n### Privacy\n\nYour privacy is important to us. Please review our [Privacy Policy](/privacy) for details on how we collect, use, and protect your personal information, including your phone number and SMS opt-in data.'
)
WHERE key = 'terms_content'
  AND (value #>> '{}') NOT LIKE '%SMS/Text Messaging Terms%';

-- Append SMS Privacy section to privacy_content (if it doesn't already contain it)
UPDATE site_settings
SET value = to_jsonb(
  (value #>> '{}') || E'\n\n---\n\n## SMS/Text Messaging Opt-In & Data\n\nWhen you provide your phone number through our website forms (Get Started, Contact Us) and check the SMS consent box, you opt in to receive text messages from STR Fitness LLC we are DBA as STR. We collect your phone number solely for the following purposes:\n\n- Responding to your inquiries and service requests\n- Sending appointment reminders and scheduling confirmations\n- Providing account updates and membership notifications\n- Delivering promotional offers and gym updates (only if you opt in)\n\n**Opt-in method:** By checking the SMS consent checkbox on our website forms, you expressly agree to receive text messages. This consent is not a condition of purchasing any goods or services.\n\n**Message frequency:** Message frequency varies based on your interactions and account activity. You may receive up to 10 messages per month.\n\n**Opt-out:** You can opt out at any time by replying STOP to any text message. You will receive a confirmation message and no further texts will be sent. You may also contact us at info@trainwithstr.com to opt out.\n\n**Help:** Reply HELP to any text message for assistance, or contact us at info@trainwithstr.com.\n\n**Message and data rates:** Standard message and data rates from your wireless carrier may apply to messages you send and receive.\n\n## Mobile Information Sharing\n\nWe do not sell, rent, lease, or share your mobile phone number or any personal information collected via SMS/text messaging with third parties or affiliates for marketing or promotional purposes. Your phone number and opt-in data are used solely by STR Fitness LLC we are DBA as STR for the purposes described in this Privacy Policy.\n\nWe may share your information only with service providers who assist in delivering text messages (e.g., our messaging platform), and they are contractually obligated to protect your data and use it only for the purpose of providing their services to us.'
)
WHERE key = 'privacy_content'
  AND (value #>> '{}') NOT LIKE '%SMS/Text Messaging Opt-In%';
